
services:

  frontend:
    build:
      dockerfile: dockerfile
    command: julia Main.jl frontend
    env_file: .env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}

  data:
    build:
      dockerfile: dockerfile
    command: julia Main.jl data
    env_file: .env
    ports:
      - ${DATA_PORT}:${DATA_PORT}
    volumes:
      - ${DATA_SOURCE}:${DATA_TARGET}:shared
  
  training:
    build:
      dockerfile: dockerfile
    command: julia Main.jl training
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - ${VISUALIZER_PORT_1}:${VISUALIZER_PORT_1}
      - ${VISUALIZER_PORT_2}:${VISUALIZER_PORT_2}

