
services:

  frontend:
    build:
      dockerfile: dockerfile
    command: julia ${SRC_TARGET}/Main.jl frontend
    env_file: .env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ${SRC_SOURCE}:${SRC_TARGET}:shared
  
  data:
    build:
      dockerfile: dockerfile
    command: julia ${SRC_TARGET}/Main.jl data
    env_file: .env
    ports:
      - ${DATA_PORT}:${DATA_PORT}
    volumes:
      - ${DATA_SOURCE}:${DATA_TARGET}:shared
      - ${SRC_SOURCE}:${SRC_TARGET}:shared
  
  training:
    build:
      dockerfile: dockerfile
    command: julia ${SRC_TARGET}/Main.jl training
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - ${TRAINING_PORT}:${TRAINING_PORT}
    volumes:
      - ${SRC_SOURCE}:${SRC_TARGET}:shared

  test:
    build:
      dockerfile: dockerfile
    command: julia ${SRC_TARGET}/Main.jl test
    env_file: .env
    ports:
      - ${DATA_PORT}:${DATA_PORT}
      - ${TRAINING_PORT}:${TRAINING_PORT}
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ${DATA_SOURCE}:${DATA_TARGET}:shared
      - ${SRC_SOURCE}:${SRC_TARGET}:shared



