# FROM nvidia/cuda:12.2.0-devel-ubuntu20.04 as builder
FROM julia:1.9.3-bullseye

ARG DEBIAN_FRONTEND=noninteractive

ENV LD_LIBRARY_PATH /usr/local/cuda/lib64/stubs/:$LD_LIBRARY_PATH

# set working directory
WORKDIR /VAE

# copy code into the container 
COPY src/ .

# copy data into the container
COPY data data

# install dependencies
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y build-essential libatomic1 python3 gfortran perl wget m4 cmake pkg-config curl
RUN apt-get install -y git

RUN \
git clone https://github.com/JuliaLang/julia.git && \
cd julia && \
git checkout v1.9.3 && \
make && \
export PATH=$PATH:/VAE/julia

RUN julia Main.jl

RUN julia -e 'using CUDA; CUDA.set_runtime_version!(v"12.2")'
RUN julia -e 'using CUDA; CUDA.precompile_runtime()'

CMD []